In [2]:
from platform import python_version

print(python_version())

3.10.9


In [3]:
import numpy as np
x = [1, 2, 3, 4, 5]
print(type(x))
print(len(x))
len(x)

<class 'list'>
5


5

In [4]:
x1 = [[1, 2, 3, 4], [5, 6, 7, 8]]
print(type(x1))
print(len(x1))

<class 'list'>
2


In [5]:
X1 = np.array(x1, dtype=np.double)
X1.shape

(2, 4)

In [6]:
(2, 4)
y1 = np.array([
    [9, 8, 7, 6],
    [1, 3, 5, 7]
], dtype=np.float16)
print(X1 - y1)

[[-8. -6. -4. -2.]
 [ 4.  3.  2.  1.]]


In [7]:
x = np.arange(1, 50, 5, dtype=np.uint)
print(x)
print(type(x))

[ 1  6 11 16 21 26 31 36 41 46]
<class 'numpy.ndarray'>


In [8]:
x = np.linspace(1, 9, 80)
print(x)

[1.         1.10126582 1.20253165 1.30379747 1.40506329 1.50632911
 1.60759494 1.70886076 1.81012658 1.91139241 2.01265823 2.11392405
 2.21518987 2.3164557  2.41772152 2.51898734 2.62025316 2.72151899
 2.82278481 2.92405063 3.02531646 3.12658228 3.2278481  3.32911392
 3.43037975 3.53164557 3.63291139 3.73417722 3.83544304 3.93670886
 4.03797468 4.13924051 4.24050633 4.34177215 4.44303797 4.5443038
 4.64556962 4.74683544 4.84810127 4.94936709 5.05063291 5.15189873
 5.25316456 5.35443038 5.4556962  5.55696203 5.65822785 5.75949367
 5.86075949 5.96202532 6.06329114 6.16455696 6.26582278 6.36708861
 6.46835443 6.56962025 6.67088608 6.7721519  6.87341772 6.97468354
 7.07594937 7.17721519 7.27848101 7.37974684 7.48101266 7.58227848
 7.6835443  7.78481013 7.88607595 7.98734177 8.08860759 8.18987342
 8.29113924 8.39240506 8.49367089 8.59493671 8.69620253 8.79746835
 8.89873418 9.        ]


In [9]:
x = np.eye(2)
print(x)
print(np.eye(3, 5))

[[1. 0.]
 [0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [10]:
x = np.diag([2, 3, 4], -2)   # Replace 0 with +1 and -1
print(x)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]]


In [11]:
x = np.vander([1, 2, 3, 4], 5)
print(x)
x = np.ones((3, 3))
print(x)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
x = np.zeros((3, 2))
print(x)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [13]:
from numpy.random import default_rng
x = default_rng(22).random((2, 3)) # Change 0 to 42 or any other like 6
print(x)

[[0.36634692 0.19929538 0.08855837]
 [0.65319169 0.45933704 0.98767562]]


In [14]:
x = np.indices((1,2))
#x = np.indices((2,3))
#x = np.indices((3,3))
#x = np.indices((1,3))
print(x)

[[[0 0]]

 [[0 1]]]


In [15]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[3:4].copy()
b *= 10 # b = b*10
print(b)

[40]


In [16]:
index = np.where(a)[0] # type 1 in place of 0
index

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [17]:
a = np.array([1, 2, 3, 4])
b = np.eye(4, 4)
print(np.hstack(b))
print(np.vstack(a))

[1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
[[1]
 [2]
 [3]
 [4]]


In [18]:
C1 = np.eye(2, 2)
C2 = np.ones((2, 2))
C3 = np.zeros((2, 2))
C4 = np.diag((3, 4))
B = np.block([[C1, C2], [C3, C4]])
print(B)

[[1. 0. 1. 1.]
 [0. 1. 1. 1.]
 [0. 0. 3. 0.]
 [0. 0. 0. 4.]]


In [19]:
x = np.arange(10)
print(x)
print(x[2])  # forward index
print(x[-2])  # reverse indexing

[0 1 2 3 4 5 6 7 8 9]
2
8


In [20]:
x = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])
print(x.shape)
print(x[-1, -2])
print(x[:3, :1])

(3, 3)
8
[[1]
 [4]
 [7]]


In [21]:
x = np.arange(10)
print(x[1:9:2])
print(x[-1:-9:-2])
print(x[-2:10])
print(x[-3:3:-1])
print(x[5:])

[1 3 5 7]
[9 7 5 3]
[8 9]
[7 6 5 4]
[5 6 7 8 9]


In [22]:
X = [1, 2, 3]
Z = [4, 5, 6]
y = [a + b * 2 for a, b in zip(X, Z)]
print(y)
print(np.zeros_like(X))
print(np.ones_like(X))
print(np.empty_like(X))
print(np.full_like(X, 3))

[9, 12, 15]
[0 0 0]
[1 1 1]
[1 2 3]
[3 3 3]


In [23]:
print(np.arange(3))
print(np.arange(1, 6))
print(np.arange(1., 6., 2))
print(np.linspace(1, 6, 4))

[0 1 2]
[1 2 3 4 5]
[1. 3. 5.]
[1.         2.66666667 4.33333333 6.        ]


In [24]:
rng = np.random.default_rng()
print(rng.integers(0, 9, 3))  # excluding 9
print(rng.integers(0, 9, 3, endpoint=True))  # include 9
print(rng.random(3))
print(rng.standard_normal(3))
print(rng.uniform(0, 7, 2))
print(rng.normal(5, 2, 3))

[3 3 1]
[2 0 2]
[0.02951913 0.73485137 0.6122483 ]
[ 1.79398466 -0.56497022  0.93282719]
[0.27847838 0.82291053]
[1.10579659 2.40260543 5.54489124]


In [25]:
a = np.arange(0, 6)
print(a)
print(a[2])
print(a[2:4])
print(a[-3:])
print(a[::-2])
print(a[2::])
print(a[:2:])
b = a.copy()
print(b[:])

[0 1 2 3 4 5]
2
[2 3]
[3 4 5]
[5 3 1]
[2 3 4 5]
[0 1]
[0 1 2 3 4 5]


In [26]:
a = np.array([1, 2, 5, 8, 4, 9, 3])
b = a > 5
b = np.any(a > 5)
b = np.all(a > 5)
print(b)

False


In [27]:
print(a[a > 5])
a[a > 5] = 0
print(a)
a = np.array([1, 2, 4, 5, 7, 3, 9, 2])
a[(a >= 3) & (a <= 5)] = 0
print(a)
a = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12],
    [13, 14, 15, 16]
])
print(a.shape)
print(a[:4])

[8 9]
[1 2 5 0 4 0 3]
[1 2 0 0 7 0 9 2]
(4, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [28]:
a = np.array([1, 2, 3, 4, 5, 3, 4, 6, 7, 8, 4])
print(np.where(a > 3))
print(np.nonzero(a > 4))
print(len(a))

(array([ 3,  4,  6,  7,  8,  9, 10], dtype=int64),)
(array([4, 7, 8, 9], dtype=int64),)
11


In [29]:
a = np.array([1, 2])
b = np.array([3, 4])
print(a + b)
print(a - b)
print(a * b)
print(a / b)
print(a // b)
print(a ** b)
print(np.sqrt(a))
print(np.exp(a))
print(np.log(a))
print(np.dot(a, b))
print(np.cross(a, b))

[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]
[0 0]
[ 1 16]
[1.         1.41421356]
[2.71828183 7.3890561 ]
[0.         0.69314718]
11
-2


In [30]:

print(s.capitalize())  # Capitalize a string; prints "Hello"
print(s.upper())       # Convert a string to uppercase; prints "HELLO"
print(s.rjust(7))      # Right-justify a string, padding with spaces; prints "  hello"
print(s.center(7))     # Center a string, padding with spaces; prints " hello "
print(s.replace('l', '(ell)'))  # Replace all instances of one substring with another;
                                # prints "he(ell)(ell)o"
print('  world '.strip())  # Strip leading and trailing whitespace; prints "world"
birds = ['hen', 'pegion', 'parrot','peacock','duck']
for bird in birds:
    print(bird) # Try birds

NameError: name 's' is not defined

In [ ]:
xs = [3, 1, 2]    # Create a list
print(xs, xs[2])  # Prints "[3, 1, 2] 2"
print(xs[-1])     # Negative indices count from the end of the list; prints "2"
xs[2] = 'Mlwp'     # Lists can contain elements of different types
print(xs)         
xs.append('python')  # Add a new element to the end of the list
print(xs)         
x = xs.pop()      # Remove and return the last element of the lis

[3, 1, 2] 2
2
[3, 1, 'Mlwp']
[3, 1, 'Mlwp', 'python']


In [ ]:
a_list = list(range(8))     # range is a built-in function that creates a list of integers
print(a_list)
print(a_list[2:4])          # Get a slice from index 2 to 4 (exclusive); prints "[2, 3]"
print(a_list[2:])           # Get a slice from index 2 to the end; prints "[2, 3, 4]"
print(a_list[:2])           # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
print(a_list[:])            # Get a slice of the whole list; prints "[0, 1, 2, 3, 4]"
print(a_list[:-1])          # Slice indices can be negative; prints "[0, 1, 2, 3]"
a_list[2:4] = [9, 10]        # Assign a new sublist to a slice
print(a_list)           

[0, 1, 2, 3, 4, 5, 6, 7]
[2, 3]
[2, 3, 4, 5, 6, 7]
[0, 1]
[0, 1, 2, 3, 4, 5, 6, 7]
[0, 1, 2, 3, 4, 5, 6]
[0, 1, 9, 10, 4, 5, 6, 7]
