In [1]:
import numpy as np
X = np.array([
[3,4],
[5,3],
[6,7],
[3,5],
[6,3],
[5,5],
[4,5]
])
k1 = np.array([2,3])
k2 = np.array([5,3])
# iter 1
Ed_1 = []
Ed_2 = []
for i in range(len(X)):
    Ed1 = np.sqrt((X[i,0]-k1[0])**2+(X[i,1]-k1[1])**2)
    Ed2 = np.sqrt((X[i,0]-k2[0])**2+(X[i,1]-k2[1])**2)
    Ed_1.append(Ed1)
    Ed_2.append(Ed2)
compare_1 = np.less_equal(Ed_1,Ed_2)
print(compare_1)
indices_c1=[]
indices_c2 = []
for i, Val in enumerate(compare_1):
    if Val == True:
        indices_c1.append(i)
    else:
        indices_c2.append(i)
print(indices_c1)
print(indices_c2)
C1 = X[indices_c1]
print(X)
print(C1)
C2 = X[indices_c2]
print(C2)
k1 = np.array([np.average(C1[:,0]), np.average(C1[:,1])])
k2 = np.array([np.average(C2[:,0]), np.average(C2[:,1])])
print(k1)
print(k2)
# iter 2
Ed_1 = []
Ed_2 = []
for i in range(len(X)):
    Ed1 = np.sqrt((X[i,0]-k1[0])**2+(X[i,1]-k1[1])**2)
    Ed2 = np.sqrt((X[i,0]-k2[0])**2+(X[i,1]-k2[1])**2)
    Ed_1.append(Ed1)
    Ed_2.append(Ed2)
compare_1 = np.less_equal(Ed_1,Ed_2)
print(compare_1)
indices_c1=[]
indices_c2 = []
for i, Val in enumerate(compare_1):
    if Val == True:
        indices_c1.append(i)
    else:
        indices_c2.append(i)
print(indices_c1)
print(indices_c2)
C1 = X[indices_c1]
print(X)
print(C1)
C2 = X[indices_c2]
print(C2)
k1 = np.array([np.average(C1[:,0]), np.average(C1[:,1])])
k2 = np.array([np.average(C2[:,0]), np.average(C2[:,1])])
print(k1)
print(k2)
# iter 3
Ed_1 = []
Ed_2 = []
for i in range(len(X)):
    Ed1 = np.sqrt((X[i,0]-k1[0])**2+(X[i,1]-k1[1])**2)
    Ed2 = np.sqrt((X[i,0]-k2[0])**2+(X[i,1]-k2[1])**2)
    Ed_1.append(Ed1)
    Ed_2.append(Ed2)
compare_1 = np.less_equal(Ed_1,Ed_2)
print(compare_1)
indices_c1=[]
indices_c2 = []
for i, Val in enumerate(compare_1):
    if Val == True:
        indices_c1.append(i)
    else:
        indices_c2.append(i)
print(indices_c1)
print(indices_c2)
C1 = X[indices_c1]
print(X)
print(C1)
C2 = X[indices_c2]
print(C2)
k1 = np.array([np.average(C1[:,0]), np.average(C1[:,1])])
k2 = np.array([np.average(C2[:,0]), np.average(C2[:,1])])
print(k1)
print(k2)
# using sklearn
from sklearn.cluster import KMeans
kmeans = KMeans(n_clusters=2)
pred_y = kmeans.fit(X)
print(pred_y.cluster_centers_)
print(kmeans.predict)

[ True False False  True False False False]
[0, 3]
[1, 2, 4, 5, 6]
[[3 4]
 [5 3]
 [6 7]
 [3 5]
 [6 3]
 [5 5]
 [4 5]]
[[3 4]
 [3 5]]
[[5 3]
 [6 7]
 [6 3]
 [5 5]
 [4 5]]
[3.  4.5]
[5.2 4.6]
[ True False False  True False False  True]
[0, 3, 6]
[1, 2, 4, 5]
[[3 4]
 [5 3]
 [6 7]
 [3 5]
 [6 3]
 [5 5]
 [4 5]]
[[3 4]
 [3 5]
 [4 5]]
[[5 3]
 [6 7]
 [6 3]
 [5 5]]
[3.33333333 4.66666667]
[5.5 4.5]
[ True False False  True False False  True]
[0, 3, 6]
[1, 2, 4, 5]
[[3 4]
 [5 3]
 [6 7]
 [3 5]
 [6 3]
 [5 5]
 [4 5]]
[[3 4]
 [3 5]
 [4 5]]
[[5 3]
 [6 7]
 [6 3]
 [5 5]]
[3.33333333 4.66666667]
[5.5 4.5]
[[5.5 3. ]
 [4.2 5.2]]
<bound method KMeans.predict of KMeans(n_clusters=2)>


In [2]:
import numpy as np
X = np.array([2,3,4,7,9,10,14,20,25,30])
k1=4
k2=10
Ed1=np.sqrt(np.square(X-k1))
Ed2=np.sqrt(np.square(X-k2))
print(Ed1)
print(Ed2)
compare_1 = np.less_equal(Ed1,Ed2)
print(compare_1)
indices_c1=[]
indices_c2=[]
for i, Val in enumerate(compare_1):
    if Val == True:
        indices_c1.append(i)
    elif Val == False:
        indices_c2.append(i)
print('c1_idx =',indices_c1)
print('c2_idx =', indices_c2)
print('c1 =', X[indices_c1])
print('c2 =', X[indices_c2])
# calculate new k1 and k2 itr1
c1 = X[indices_c1]
c2 = X[indices_c2]
k1 = np.average(c1)
k2 = np.average(c2)
Ed1=np.sqrt(np.square(X-k1))
Ed2=np.sqrt(np.square(X-k2))
print(Ed1)
print(Ed2)
compare_1 = np.less_equal(Ed1,Ed2)
print(compare_1)
indices_c1=[]
indices_c2=[]
for i, Val in enumerate(compare_1):
    if Val == True:
        indices_c1.append(i)
    elif Val == False:
indices_c2.append(i)
print('c1_idx =',indices_c1)
print('c2_idx =', indices_c2)
print('c1 =', X[indices_c1])
print('c2 =', X[indices_c2])
# calculate new k1 and k2 itr2
c1 = X[indices_c1]
c2 = X[indices_c2]
k1 = np.average(c1)
k2 = np.average(c2)
Ed1=np.sqrt(np.square(X-k1))
Ed2=np.sqrt(np.square(X-k2))
print(Ed1)
print(Ed2)
compare_1 = np.less_equal(Ed1,Ed2)
print(compare_1)
indices_c1=[]
indices_c2=[]
for i, Val in enumerate(compare_1):
if Val == True:
indices_c1.append(i)
elif Val == False:
indices_c2.append(i)
print('c1_idx =',indices_c1)
print('c2_idx =', indices_c2)
print('c1 =', X[indices_c1])
print('c2 =', X[indices_c2])
print(k1,k2)

IndentationError: expected an indented block (803991137.py, line 39)