In [1]:
#sqrt of a list of numbers and print the result as a numpy array
import numpy as np
import random
list=[]
n=50
for i in range(n):
    list.append(random.randint(1,49))
print(list)
  
  #sqrt of list
b=np.sqrt(list)

print()
print(np.array(b))

[34, 20, 43, 48, 31, 33, 46, 46, 11, 48, 35, 5, 11, 41, 35, 6, 42, 45, 20, 7, 16, 3, 3, 21, 1, 49, 18, 19, 20, 2, 20, 18, 12, 27, 9, 45, 27, 28, 30, 7, 47, 7, 8, 43, 36, 47, 36, 33, 13, 49]

[5.83095189 4.47213595 6.55743852 6.92820323 5.56776436 5.74456265
 6.78232998 6.78232998 3.31662479 6.92820323 5.91607978 2.23606798
 3.31662479 6.40312424 5.91607978 2.44948974 6.4807407  6.70820393
 4.47213595 2.64575131 4.         1.73205081 1.73205081 4.58257569
 1.         7.         4.24264069 4.35889894 4.47213595 1.41421356
 4.47213595 4.24264069 3.46410162 5.19615242 3.         6.70820393
 5.19615242 5.29150262 5.47722558 2.64575131 6.8556546  2.64575131
 2.82842712 6.55743852 6.         6.8556546  6.         5.74456265
 3.60555128 7.        ]


In [27]:
# Python program to swap elements at first and last position in list
import numpy as np
# Swap function
def swapPositions(list, pos1, pos2):
	
	list[pos1], list[pos2] = list[pos2], list[pos1]
	return list

# Driver function
n=10
List = [i for i in range(n)]
pos1, pos2 = 1, 10

print(swapPositions(List, pos1-1, pos2-1))


[9, 1, 2, 3, 4, 5, 6, 7, 8, 0]


In [3]:
# 2 arrays mathematical operations
import numpy as np
from numpy import random
x=random.randint(100, size=(5))
y=random.randint(100, size=(5))
print(x)
print(y)
#mathematical operations
print()
#addition 
z = x + y
print(z)
#subtraction
z = x - y
print(z)
#multiplication
z = x * y
print(z)
#divison
z = x / y
print(z)



[71 22 90 67 50]
[95 10 87 82 33]

[166  32 177 149  83]
[-24  12   3 -15  17]
[6745  220 7830 5494 1650]
[0.74736842 2.2        1.03448276 0.81707317 1.51515152]
